/**
 * Creatures 3/DS Classification System Utilities
 * 
 * This file provides utility functions for working with the Creatures 3 classification
 * system. It imports data from classification-data.js which is auto-generated by the
 * extract-classification-data.js script.
 * 
 * The classification system uses a three-tier hierarchy:
 * - Family: Top-level category (1-255)
 * - Genus: Sub-category within family (1-255)  
 * - Species: Specific variant within genus (1-65535)
 * 
 * Usage:
 *   import { getClassifierName, searchClassifiers } from './classification.js';
 *   
 *   const name = getClassifierName(1, 1, 1); // "Rock near Norn pool"
 *   const toys = searchClassifiers('toy');   // Array of toy classifiers
 */

import { 
  FAMILIES, 
  GENUS, 
  KNOWN_CLASSIFIERS, 
  GENERATION_INFO,
  STATISTICS
} from './classification-data.js';

/**
 * Get human readable name for a complete classifier
 * @param {number} family - Family number (1-255)
 * @param {number} genus - Genus number (1-255) 
 * @param {number} species - Species number (1-65535)
 * @returns {string|null} Human readable name or null if not found
 */
export function getClassifierName(family, genus, species) {
  const found = KNOWN_CLASSIFIERS.find(c => 
    c.family === family && c.genus === genus && c.species === species
  );
  return found ? found.name : null;
}

/**
 * Get complete classifier information
 * @param {number} family - Family number
 * @param {number} genus - Genus number
 * @param {number} species - Species number
 * @returns {object|null} Complete classifier object or null if not found
 */
export function getClassifierInfo(family, genus, species) {
  return KNOWN_CLASSIFIERS.find(c => 
    c.family === family && c.genus === genus && c.species === species
  ) || null;
}

/**
 * Get family information
 * @param {number} family - Family number
 * @returns {object|null} Family info with name and description, or null
 */
export function getFamilyInfo(family) {
  return FAMILIES[family] || null;
}

/**
 * Get genus information  
 * @param {number} family - Family number
 * @param {number} genus - Genus number
 * @returns {object|null} Genus info with name and description, or null
 */
export function getGenusInfo(family, genus) {
  return GENUS[family] && GENUS[family][genus] || null;
}

/**
 * Get a formatted string representation of a classifier
 * @param {number} family - Family number
 * @param {number} genus - Genus number
 * @param {number} species - Species number
 * @param {boolean} includeNames - Whether to include human-readable names
 * @returns {string} Formatted classifier string
 */
export function formatClassifier(family, genus, species, includeNames = true) {
  const classNumber = `${family} ${genus} ${species}`;
  
  if (!includeNames) {
    return classNumber;
  }
  
  const parts = [];
  
  // Add family info
  const familyInfo = getFamilyInfo(family);
  if (familyInfo) {
    parts.push(`Family ${family} (${familyInfo.name})`);
  } else {
    parts.push(`Family ${family}`);
  }
  
  // Add genus info
  const genusInfo = getGenusInfo(family, genus);
  if (genusInfo) {
    parts.push(`Genus ${genus} (${genusInfo.name})`);
  } else {
    parts.push(`Genus ${genus}`);
  }
  
  // Add species info
  const classifierName = getClassifierName(family, genus, species);
  if (classifierName) {
    parts.push(`Species ${species} (${classifierName})`);
  } else {
    parts.push(`Species ${species}`);
  }
  
  return `${classNumber}: ${parts.join(' → ')}`;
}

/**
 * Validate classifier numbers against game limits
 * @param {number} family - Family (1-255)
 * @param {number} genus - Genus (1-255)
 * @param {number} species - Species (1-65535 for C3/DS)
 * @returns {object} Validation result with isValid boolean and errors array
 */
export function validateClassifier(family, genus, species) {
  const errors = [];
  
  if (!Number.isInteger(family) || family < 1 || family > 255) {
    errors.push('Family must be an integer between 1 and 255');
  }
  
  if (!Number.isInteger(genus) || genus < 1 || genus > 255) {
    errors.push('Genus must be an integer between 1 and 255');
  }
  
  if (!Number.isInteger(species) || species < 1 || species > 65535) {
    errors.push('Species must be an integer between 1 and 65535');
  }
  
  return {
    isValid: errors.length === 0,
    errors
  };
}

/**
 * Check if a classifier is valid (simple boolean version)
 * @param {number} family - Family (1-255)
 * @param {number} genus - Genus (1-255)
 * @param {number} species - Species (1-65535)
 * @returns {boolean} True if all numbers are within valid ranges
 */
export function isValidClassifier(family, genus, species) {
  return validateClassifier(family, genus, species).isValid;
}

/**
 * Find all known classifiers for a specific family
 * @param {number} family - Family number
 * @returns {array} Array of matching classifier objects
 */
export function findClassifiersByFamily(family) {
  return KNOWN_CLASSIFIERS.filter(c => c.family === family);
}

/**
 * Find all known classifiers for a specific genus within a family
 * @param {number} family - Family number
 * @param {number} genus - Genus number
 * @returns {array} Array of matching classifier objects
 */
export function findClassifiersByGenus(family, genus) {
  return KNOWN_CLASSIFIERS.filter(c => c.family === family && c.genus === genus);
}

/**
 * Search classifiers by name (case-insensitive)
 * @param {string} searchTerm - Search term to match against names
 * @returns {array} Array of matching classifier objects
 */
export function searchClassifiers(searchTerm) {
  const term = searchTerm.toLowerCase();
  return KNOWN_CLASSIFIERS.filter(c => 
    c.name.toLowerCase().includes(term)
  );
}

/**
 * Search classifiers by contributor
 * @param {string} contributor - Contributor name
 * @returns {array} Array of matching classifier objects
 */
export function findClassifiersByContributor(contributor) {
  return KNOWN_CLASSIFIERS.filter(c => 
    c.contributor.toLowerCase() === contributor.toLowerCase()
  );
}

/**
 * Get all unique families present in the known classifiers
 * @returns {array} Sorted array of family numbers
 */
export function getKnownFamilies() {
  return [...new Set(KNOWN_CLASSIFIERS.map(c => c.family))].sort((a, b) => a - b);
}

/**
 * Get all unique genera for a specific family
 * @param {number} family - Family number
 * @returns {array} Sorted array of genus numbers
 */
export function getKnownGenera(family) {
  return [...new Set(
    KNOWN_CLASSIFIERS
      .filter(c => c.family === family)
      .map(c => c.genus)
  )].sort((a, b) => a - b);
}

/**
 * Get all unique species for a specific genus within a family
 * @param {number} family - Family number
 * @param {number} genus - Genus number
 * @returns {array} Sorted array of species numbers
 */
export function getKnownSpecies(family, genus) {
  return [...new Set(
    KNOWN_CLASSIFIERS
      .filter(c => c.family === family && c.genus === genus)
      .map(c => c.species)
  )].sort((a, b) => a - b);
}

/**
 * Get all unique contributors in the database
 * @returns {array} Array of contributor names
 */
export function getContributors() {
  return [...new Set(KNOWN_CLASSIFIERS.map(c => c.contributor))].filter(c => c);
}

/**
 * Parse a class number string into components
 * @param {string} classNumberString - Class number as string (e.g., "1 2 3")
 * @returns {object|null} Object with family, genus, species properties or null if invalid
 */
export function parseClassNumber(classNumberString) {
  const parts = classNumberString.trim().split(/\s+/).map(n => parseInt(n));
  
  if (parts.length !== 3 || parts.some(isNaN)) {
    return null;
  }
  
  const [family, genus, species] = parts;
  
  if (!isValidClassifier(family, genus, species)) {
    return null;
  }
  
  return { family, genus, species };
}

/**
 * Get statistics about the classification data
 * @returns {object} Statistics object with counts and ranges
 */
export function getClassificationStatistics() {
  return {
    ...STATISTICS,
    knownFamilies: getKnownFamilies(),
    contributors: getContributors()
  };
}

/**
 * Get information about the data generation
 * @returns {object} Generation metadata including timestamp and source
 */
export function getGenerationInfo() {
  return GENERATION_INFO;
}

/**
 * Check if a classifier is documented (has a known name)
 * @param {number} family - Family number
 * @param {number} genus - Genus number
 * @param {number} species - Species number
 * @returns {boolean} True if the classifier has a documented name
 */
export function isDocumented(family, genus, species) {
  return getClassifierName(family, genus, species) !== null;
}

/**
 * Get a suggested family and genus for a new classifier
 * This helps developers choose appropriate classifications for new agents
 * @param {string} objectType - Type of object (e.g., 'toy', 'food', 'creature')
 * @returns {object|null} Suggested family and genus info, or null if no suggestion
 */
export function suggestClassification(objectType) {
  const type = objectType.toLowerCase();
  
  // Common object type mappings
  const suggestions = {
    'toy': { family: 2, genus: 21, info: 'Simple Objects → Toy' },
    'food': { family: 2, genus: 11, info: 'Simple Objects → Food' },
    'plant': { family: 2, genus: 4, info: 'Simple Objects → Good plant' },
    'seed': { family: 2, genus: 3, info: 'Simple Objects → Seed' },
    'fruit': { family: 2, genus: 8, info: 'Simple Objects → Good Fruit' },
    'bug': { family: 2, genus: 13, info: 'Simple Objects → Good Bug' },
    'critter': { family: 2, genus: 15, info: 'Simple Objects → Good Critter' },
    'button': { family: 2, genus: 12, info: 'Simple Objects → Button' },
    'door': { family: 2, genus: 2, info: 'Simple Objects → Door' },
    'tool': { family: 2, genus: 24, info: 'Simple Objects → Tool' },
    'potion': { family: 2, genus: 25, info: 'Simple Objects → Potion' },
    'vendor': { family: 2, genus: 23, info: 'Simple Objects → Vendor' },
    'lift': { family: 3, genus: 1, info: 'Compound Objects → Lift' },
    'teleporter': { family: 3, genus: 2, info: 'Compound Objects → Teleporter' },
    'machine': { family: 3, genus: 3, info: 'Compound Objects → Machinery' },
    'vehicle': { family: 3, genus: 10, info: 'Compound Objects → Vehicle' },
    'norn': { family: 4, genus: 1, info: 'Creatures → Norn' },
    'grendel': { family: 4, genus: 2, info: 'Creatures → Grendel' },
    'ettin': { family: 4, genus: 3, info: 'Creatures → Ettin' }
  };
  
  return suggestions[type] || null;
}

// Re-export data constants for direct access if needed
export { FAMILIES, GENUS, KNOWN_CLASSIFIERS, GENERATION_INFO, STATISTICS };
