// Creatures 3 Poses Database
// Extracted from SUPPORT_FILES/PoseName.txt
const CREATURES_POSES = [
  { id: 0, name: 'Reach low near', description: '' },
  { id: 1, name: 'Reach lowish near', description: '' },
  { id: 2, name: 'Reach highish near', description: '' },
  { id: 3, name: 'Reach high near', description: '' },
  { id: 4, name: 'Reach low medium', description: '' },
  { id: 5, name: 'Reach lowish medium', description: '' },
  { id: 6, name: 'Reach highish medium', description: '' },
  { id: 7, name: 'Reach high medium', description: '' },
  { id: 8, name: 'Reach low far', description: '' },
  { id: 9, name: 'Reach lowish far', description: '' },
  { id: 10, name: 'Reach highish far', description: '' },
  { id: 11, name: 'Reach high far', description: '' },
  { id: 12, name: 'Stand', description: '' },
  { id: 13, name: 'Normal 1', description: '' },
  { id: 14, name: 'Normal 2', description: '' },
  { id: 15, name: 'Normal 3', description: '' },
  { id: 16, name: 'Normal 4', description: '' },
  { id: 17, name: 'Pained 1', description: '' },
  { id: 18, name: 'Pained 2', description: '' },
  { id: 19, name: 'Pained 3', description: '' },
  { id: 20, name: 'Pained 4', description: '' },
  { id: 21, name: 'Tired 1', description: '' },
  { id: 22, name: 'Tired 2', description: '' },
  { id: 23, name: 'Tired 3', description: '' },
  { id: 24, name: 'Tired 4', description: '' },
  { id: 25, name: 'Scared 1', description: '' },
  { id: 26, name: 'Scared 2', description: '' },
  { id: 27, name: 'Scared 3', description: '' },
  { id: 28, name: 'Scared 4', description: '' },
  { id: 29, name: 'Anger 1', description: '' },
  { id: 30, name: 'Anger 2', description: '' },
  { id: 31, name: 'Anger 3', description: '' },
  { id: 32, name: 'Anger 4', description: '' },
  { id: 33, name: 'To camera', description: '' },
  { id: 34, name: 'Express general need', description: '' },
  { id: 35, name: 'Express pain', description: '' },
  { id: 36, name: 'Express hunger', description: '' },
  { id: 37, name: 'Express tired', description: '' },
  { id: 38, name: 'Express lonely', description: '' },
  { id: 39, name: 'Express fear', description: '' },
  { id: 40, name: 'Toe tap 1', description: '' },
  { id: 41, name: 'Toe tap 2', description: '' },
  { id: 42, name: 'Angry 5', description: '' },
  { id: 43, name: 'Angry 6', description: '' },
  { id: 44, name: 'Swing arms 1', description: '' },
  { id: 45, name: 'Swing arms 2', description: '' },
  { id: 46, name: 'Shiver 1', description: '' },
  { id: 47, name: 'Shiver 2', description: '' },
  { id: 48, name: 'Slap Norn 1', description: '' },
  { id: 49, name: 'Retreat 1', description: '' },
  { id: 50, name: 'Retreat 2', description: '' },
  { id: 51, name: 'Retreat 3', description: '' },
  { id: 52, name: 'Retreat 4', description: '' },
  { id: 53, name: 'Flee 1', description: '' },
  { id: 54, name: 'Flee 2', description: '' },
  { id: 55, name: 'Flee 3', description: '' },
  { id: 56, name: 'Flee 4', description: '' },
  { id: 57, name: 'Rest', description: '' },
  { id: 58, name: 'Sleep', description: '' },
  { id: 59, name: 'East', description: '' },
  { id: 60, name: 'West', description: '' },
  { id: 61, name: 'Bored 1', description: '' },
  { id: 62, name: 'Bored 2', description: '' },
  { id: 63, name: 'Bored 3', description: '' },
  { id: 64, name: 'Bored 4', description: '' },
  { id: 65, name: 'Throw 1', description: '' },
  { id: 66, name: 'Throw 2', description: '' },
  { id: 67, name: 'Kick 1', description: '' },
  { id: 68, name: 'Kick 2', description: '' },
  { id: 69, name: 'Drum 1', description: '' },
  { id: 70, name: 'Drum 2', description: '' },
  { id: 71, name: 'Sneeze 1', description: '' },
  { id: 72, name: 'Sneeze 2', description: '' },
  { id: 73, name: 'Eat 1', description: '' },
  { id: 74, name: 'Eat 2', description: '' },
  { id: 75, name: 'Startled', description: '' },
  { id: 76, name: 'Kiss', description: '' },
  { id: 77, name: 'Dead', description: '' },
  { id: 78, name: 'Limp 1', description: '' },
  { id: 79, name: 'Limp 2', description: '' },
  { id: 80, name: 'Limp 3', description: '' },
  { id: 81, name: 'Limp 4', description: '' },
  { id: 82, name: 'Stagger 1', description: '' },
  { id: 83, name: 'Stagger 2', description: '' },
  { id: 84, name: 'Stagger 3', description: '' },
  { id: 85, name: 'Stagger 4', description: '' },
  { id: 86, name: 'Downhill 1', description: '' },
  { id: 87, name: 'Downhill 2', description: '' },
  { id: 88, name: 'Downhill 3', description: '' },
  { id: 89, name: 'Downhill 4', description: '' },
  { id: 90, name: 'Uphill 1', description: '' },
  { id: 91, name: 'Uphill 2', description: '' },
  { id: 92, name: 'Uphill 3', description: '' },
  { id: 93, name: 'Uphill 4', description: '' },
  { id: 94, name: 'Run 1', description: '' },
  { id: 95, name: 'Run 2', description: '' },
  { id: 96, name: 'Run 3', description: '' },
  { id: 97, name: 'Run 4', description: '' },
  { id: 98, name: 'Cough 1', description: '' },
  { id: 99, name: 'Cough 2', description: '' },
  { id: 100, name: 'Cough 3', description: '' },
  { id: 101, name: 'Cough 4', description: '' },
  { id: 102, name: 'Pushed 1', description: '' },
  { id: 103, name: 'Pushed 2', description: '' },
  { id: 104, name: 'Pushed 3', description: '' },
  { id: 105, name: 'Pushed 4', description: '' },
  { id: 106, name: 'Sneeze 3', description: '' },
  { id: 107, name: 'Lay egg 1', description: '' },
  { id: 108, name: 'Lay egg 2', description: '' },
  { id: 109, name: 'Lay egg 3', description: '' },
  { id: 110, name: 'Lay egg 4', description: '' },
  { id: 111, name: 'Slap Norn 2', description: '' },
  { id: 112, name: 'Slap Norn 3', description: '' },
  { id: 113, name: 'Slap Norn 4', description: '' },
  { id: 114, name: 'Slap Norn 5', description: '' },
  { id: 115, name: 'Falling 1', description: '' },
  { id: 116, name: 'Falling 2', description: '' },
  { id: 117, name: 'Impact 1', description: '' },
  { id: 118, name: 'Impact 2', description: '' },
  { id: 119, name: 'Impact 3', description: '' },
  { id: 120, name: 'Impact 4', description: '' },
  { id: 121, name: 'Impact 5', description: '' },
  { id: 122, name: 'Yawn 1', description: '' },
  { id: 123, name: 'Yawn 2', description: '' },
  { id: 124, name: 'Yawn 3', description: '' },
  { id: 125, name: 'Dance 1', description: '' },
  { id: 126, name: 'Dance 2', description: '' },
  { id: 127, name: 'Dance 3', description: '' },
  { id: 128, name: 'Dance 4', description: '' },
  { id: 129, name: 'Dance 5', description: '' },
  { id: 130, name: 'Dance 6', description: '' },
  { id: 131, name: 'Pushed behind 1', description: '' },
  { id: 132, name: 'Pushed behind 2', description: '' },
  { id: 133, name: 'Pushed behind 3', description: '' },
  { id: 134, name: 'Pushed behind 4', description: '' },
  { id: 135, name: 'Running 1', description: '' },
  { id: 136, name: 'Running 2', description: '' },
  { id: 137, name: 'Running 3', description: '' },
  { id: 138, name: 'Running 4', description: '' },
  { id: 139, name: 'Sexy 1', description: '' },
  { id: 140, name: 'Sexy 2', description: '' },
  { id: 141, name: 'Sexy 3', description: '' },
  { id: 142, name: 'Sexy 4', description: '' },
  { id: 143, name: 'Vomit 1', description: '' },
  { id: 144, name: 'Vomit 2', description: '' },
  { id: 145, name: 'Vomit 3', description: '' },
  { id: 146, name: 'Vomit 4', description: '' },
  { id: 147, name: 'Pick up 1', description: '' },
  { id: 148, name: 'Pick up 2', description: '' },
  { id: 149, name: 'Pick up 3', description: '' },
  { id: 150, name: 'Pick up 4', description: '' },
  { id: 151, name: 'Creep 1', description: '' },
  { id: 152, name: 'Creep 2', description: '' },
  { id: 153, name: 'Creep 3', description: '' },
  { id: 154, name: 'Creep 4', description: '' },
  { id: 155, name: 'Creep 5', description: '' },
  { id: 156, name: 'Jive 1', description: '' },
  { id: 157, name: 'Jive 2', description: '' },
  { id: 158, name: 'Jive 3', description: '' },
  { id: 159, name: 'Jive 4', description: '' },
  { id: 160, name: 'Jive 5', description: '' },
  { id: 161, name: 'Vomit 5', description: '' },
  { id: 162, name: 'Teeter 1', description: '' },
  { id: 163, name: 'Teeter 2', description: '' },
  { id: 164, name: 'Teeter 3', description: '' },
  { id: 165, name: 'Teeter 4', description: '' },
  { id: 166, name: 'Teeter 5', description: '' },
  { id: 167, name: 'Totter 1', description: '' },
  { id: 168, name: 'Totter 2', description: '' },
  { id: 169, name: 'Totter 3', description: '' },
  { id: 170, name: 'Totter 4', description: '' },
  { id: 171, name: 'Reward', description: '' },
  { id: 172, name: 'Punishment', description: '' },
  { id: 173, name: '173', description: '' },
  { id: 174, name: '174', description: '' },
  { id: 175, name: '175', description: '' },
  { id: 176, name: '176', description: '' },
  { id: 177, name: '177', description: '' },
  { id: 178, name: '178', description: '' },
  { id: 179, name: '179', description: '' },
  { id: 180, name: '180', description: '' },
  { id: 181, name: '181', description: '' },
  { id: 182, name: '182', description: '' },
  { id: 183, name: '183', description: '' },
  { id: 184, name: '184', description: '' },
  { id: 185, name: '185', description: '' },
  { id: 186, name: '186', description: '' },
  { id: 187, name: '187', description: '' },
  { id: 188, name: '188', description: '' },
  { id: 189, name: '189', description: '' },
  { id: 190, name: '190', description: '' },
  { id: 191, name: '191', description: '' },
  { id: 192, name: '192', description: '' },
  { id: 193, name: '193', description: '' },
  { id: 194, name: '194', description: '' },
  { id: 195, name: '195', description: '' },
  { id: 196, name: '196', description: '' },
  { id: 197, name: '197', description: '' },
  { id: 198, name: '198', description: '' },
  { id: 199, name: '199', description: '' },
  { id: 200, name: '200', description: '' },
  { id: 201, name: '201', description: '' },
  { id: 202, name: '202', description: '' },
  { id: 203, name: '203', description: '' },
  { id: 204, name: '204', description: '' },
  { id: 205, name: '205', description: '' },
  { id: 206, name: '206', description: '' },
  { id: 207, name: '207', description: '' },
  { id: 208, name: '208', description: '' },
  { id: 209, name: '209', description: '' },
  { id: 210, name: '210', description: '' },
  { id: 211, name: '211', description: '' },
  { id: 212, name: '212', description: '' },
  { id: 213, name: '213', description: '' },
  { id: 214, name: '214', description: '' },
  { id: 215, name: '215', description: '' },
  { id: 216, name: '216', description: '' },
  { id: 217, name: '217', description: '' },
  { id: 218, name: '218', description: '' },
  { id: 219, name: '219', description: '' },
  { id: 220, name: '220', description: '' },
  { id: 221, name: '221', description: '' },
  { id: 222, name: '222', description: '' },
  { id: 223, name: '223', description: '' },
  { id: 224, name: '224', description: '' },
  { id: 225, name: '225', description: '' },
  { id: 226, name: '226', description: '' },
  { id: 227, name: '227', description: '' },
  { id: 228, name: '228', description: '' },
  { id: 229, name: '229', description: '' },
  { id: 230, name: '230', description: '' },
  { id: 231, name: '231', description: '' },
  { id: 232, name: '232', description: '' },
  { id: 233, name: '233', description: '' },
  { id: 234, name: '234', description: '' },
  { id: 235, name: '235', description: '' },
  { id: 236, name: '236', description: '' },
  { id: 237, name: '237', description: '' },
  { id: 238, name: '238', description: '' },
  { id: 239, name: '239', description: '' },
  { id: 240, name: '240', description: '' },
  { id: 241, name: '241', description: '' },
  { id: 242, name: '242', description: '' },
  { id: 243, name: '243', description: '' },
  { id: 244, name: '244', description: '' },
  { id: 245, name: '245', description: '' },
  { id: 246, name: '246', description: '' },
  { id: 247, name: '247', description: '' },
  { id: 248, name: '248', description: '' },
  { id: 249, name: '249', description: '' },
  { id: 250, name: '250', description: '' },
  { id: 251, name: '251', description: '' },
  { id: 252, name: '252', description: '' },
  { id: 253, name: '253', description: '' },
  { id: 254, name: '254', description: '' },
  { id: 255, name: '255', description: '' }
];

// Export for use in the application
// Browser environment
if (typeof window !== 'undefined') {
  window.CREATURES_POSES = CREATURES_POSES;
}

// Node.js/Module environment
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATURES_POSES;
}
